/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData ajuda = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aplicativo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computador = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investigate = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout__2_ = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifier_with_an_eye = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifier_with_an_eye2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_magnifier = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData running_repair_man_with_wrench_and_kit = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings__1_ = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_image_with_black_background = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_down = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caneta = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allcoments = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meuscomentarios = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fazercomentario = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ocultar = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lixeira = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
