/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData ajuda = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData aplicativo =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData computador =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData door = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData enter = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData information =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData investigate =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData logout__2_ =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData magnifier_with_an_eye =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData magnifier_with_an_eye2 =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData notification =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData password =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData qr_code = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData running_repair_man_with_wrench_and_kit =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData settings__1_ =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData user_image_with_black_background =
      const IconData(0xe810, fontFamily: _kFontFam);
}
